# .github/workflows/ci.yml
name: ci

on: [ push, pull_request ]

jobs:
  test:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    secrets:
      # Required if you plan to publish (uncomment the below)
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      disable_release: true
      disable_phpunit: true
      disable_behat: true
      moodle_branches: MOODLE_405_STABLE
      release_branches: main
      min_php: 8.1
